SLIDE_WIDTH = 16
SLIDE_HEIGHT = 9

LEFT_MARGIN = 0.2
RIGHT_MARGIN = 0.2
TOP_MARGIN = 0.2
BOTTOM_MARGIN = 0.2

MAIN_TOPIC_BOX_WIDTH = 1.6
MAIN_TOPIC_BOX_HEIGHT = 0.8

SUB_TOPIC_BOX_WIDTH = 1.2
SUB_TOPIC_BOX_HEIGHT = 0.5

DETAIL_BOX_WIDTH = 1.0
DETAIL_BOX_HEIGHT = 0.3

SPACING = 0.5
DETAIL_SPACING = 0.1